### ISSUE TITLE
Is there a way to automate the installation?

### ISSUE THREAD

**Issue by pcasaretto** [jperkins/IR-Black#1]
Like from a shell script?

**Comment by jperkins** [comment]
I can't find where Terminal stores installed themes so I resorted to having to
open the theme in Terminal. If anyone knows of another way to do this, please 
let me know!

```
# download the theme
cd ~/Downloads
curl -O https://raw.github.com/jperkins/IR-Black/master/IR_Black.terminal

# install the IR_Black theme by opening it in Terminal
open IR_Black.terminal

# if you're inclined, make IR_Black Terminal's default theme
defaults write com.apple.Terminal "Default Window Settings" -string "IR_Black"
defaults write com.apple.Terminal "Startup Window Settings" -string "IR_Black"
```

FWIW, I find IR Black's background to be too dark and the default font too large so I've modified these and a couple of other settings in my own personal install but left the settings in this theme so that it matches the original values for IR Black. I want folks who find this to get what they're expecting and not my own take on the theme.

**Comment by pcasaretto** [comment]
I'm assuming `open` opens up the terminal. Nasty.
Ill try asking in superuser to see if anyone can provide some insight.
